{% set name = "kstar" %}
{% set version = "1.0.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: 0d957ed7a2c4639d7770e840b7c668eccbf8c58de9acf1836de287f00f9eab69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
  run:

    - biopython==1.78.*

    - matplotlib-base==3.8.*
    - numpy==1.26.*
    - pandas==2.1.*
    - python>=3.10
    - requests==2.31.*
    - scipy==1.11.*
    - seaborn==0.13.*

test:
  imports:
    - kstar
    - kstar.random_experiments
    - kstar.analysis
  commands:
    - pip check
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NaegleLab

