{% set name = "kstar" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: 4bd585f61486f68f8e3ce800ad8ea678dc29524d8cfbf72d40bc670d0b8aadd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.11
  run:
    - biopython==1.81.*
    - matplotlib-base==3.8.*
    - numpy==1.26.*
    - pandas==2.1.*
    - python>=3.11
    - requests==2.31.*
    - scipy==1.11.*
    - seaborn==0.13.*

test:
  imports:
    - kstar
    - kstar.random_experiments
    - kstar.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NaegleLab

