{% set name = "kstar" %}
{% set version = "1.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: 4e485bd0fe3f223536e06ce19e4846919ffaed6ff7da19ca5391e01283ece06d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - matplotlib-base>=3.8
    - numpy>=1.26
    - pandas>=2.1
    - python>=3.9
    - scipy>=1.11
    - seaborn>=0.13
    - fpdf2>=2.5
    - requests
    - tqdm

test:
  imports:
    - kstar
    - kstar.random_experiments
    - kstar.analysis
    - kstar.dataset_processing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knaegle
