{% set name = "kstar" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: c8eb8f2622f777f05f8b9e65cc7bd104d57bf65202aef92745744a5855302ffa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - biopython
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scipy
    - seaborn
    - statsmodels

test:
  imports:
    - kstar
    - kstar.random_experiments
    - kstar.analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NaegleLab
