{% set name = "kstar" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: 2465c49455c76834f6bcf25ccd20bf558f770884ce6a3c9d23de849e5ca55db7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - biopython
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scipy
    - seaborn
    - statsmodels

test:
  imports:
    - kstar
    - kstar.normalize
    - kstar.validate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NaegleLab
