name: Track GitHub Traffic Statistics

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:        # Allow manual triggering

jobs:
  collect-traffic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo
      
      - name: Checkout stats repository
        uses: actions/checkout@v3
        with:
          repository: YourUsername/github-stats-central  # Replace with your actual central stats repo
          path: stats-repo
          token: ${{ secrets.STATS_REPO_PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib
      
      - name: Create scripts directory
        run: |
          mkdir -p ${{ github.workspace }}/stats-repo/.github/scripts/
          cp ${{ github.workspace }}/source-repo/.github/scripts/collect_traffic.py ${{ github.workspace }}/stats-repo/.github/scripts/
      
      - name: Extract repository name
        id: repo-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
      
      - name: Create output directory
        run: |
          mkdir -p ${{ github.workspace }}/stats-repo/data/${{ github.repository_owner }}/${{ steps.repo-name.outputs.repo_name }}
      
      - name: Run traffic collection script
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ steps.repo-name.outputs.repo_name }}
          OUTPUT_DIR: ${{ github.workspace }}/stats-repo/data/${{ github.repository_owner }}/${{ steps.repo-name.outputs.repo_name }}
        run: |
          echo "Environment variables:"
          echo "REPO_OWNER: $REPO_OWNER"
          echo "REPO_NAME: $REPO_NAME"
          echo "OUTPUT_DIR: $OUTPUT_DIR"
          
          cd ${{ github.workspace }}/stats-repo
          python .github/scripts/collect_traffic.py
      
      - name: Commit and push to stats repository
        run: |
          cd ${{ github.workspace }}/stats-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update traffic statistics for ${{ github.repository_owner }}/${{ steps.repo-name.outputs.repo_name }}"
          git push